# Source: cluster-api-aws/templates/machine-pool.yaml
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfig
metadata:
  name: czrj1j2gc-mp-taco
  namespace: czrj1j2gc
spec:
  joinConfiguration:
    nodeRegistration:
      kubeletExtraArgs:
        cloud-provider: aws
      name: '{{ ds.meta_data.local_hostname }}'
